apiVersion: apps/v1
kind: Deployment
metadata:
  name: g1-scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: g1-scraper
  template:
    metadata:
      labels:
        app: g1-scraper
    spec:
      containers:
        - name: g1-scraper
          image: taysonmayers/g1-scraper:latest  # Você pode subir a imagem pro Docker Hub
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["scripts/g1_scraper.py"]
